-- Invoice OCR System - Database Schema for SAP HANA Cloud
-- Table to store extracted invoice data

CREATE COLUMN TABLE INVOICES (
    INVOICE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INVOICE_NUMBER NVARCHAR(100) NOT NULL,
    VENDOR_NAME NVARCHAR(500) NOT NULL,
    UPLOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FILE_NAME NVARCHAR(500),
    FILE_SIZE_KB DECIMAL(10,2),
    RAW_TEXT NCLOB,
    STATUS NVARCHAR(50) DEFAULT 'PROCESSED',
    ERROR_MESSAGE NVARCHAR(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for faster querying
CREATE INDEX IDX_INVOICE_NUMBER ON INVOICES(INVOICE_NUMBER);
CREATE INDEX IDX_VENDOR_NAME ON INVOICES(VENDOR_NAME);
CREATE INDEX IDX_UPLOAD_TIMESTAMP ON INVOICES(UPLOAD_TIMESTAMP);

-- Comments for documentation
COMMENT ON TABLE INVOICES IS 'Stores invoice data extracted from PDFs using SAP Document Information Extraction';
COMMENT ON COLUMN INVOICES.INVOICE_ID IS 'Primary key - auto-generated unique identifier';
COMMENT ON COLUMN INVOICES.INVOICE_NUMBER IS 'Extracted invoice number from PDF';
COMMENT ON COLUMN INVOICES.VENDOR_NAME IS 'Extracted vendor/supplier name from PDF';
COMMENT ON COLUMN INVOICES.RAW_TEXT IS 'Full extracted text from Document AI for audit purposes';
COMMENT ON COLUMN INVOICES.STATUS IS 'Processing status: PROCESSED, FAILED, etc.';
